Import("env")

env.Library(
	target='ontapkv',
	source=[
            'ontapkv_global_options.cpp',
            'ontapkv_index.cpp',
            'ontapkv_init.cpp',
            'ontapkv_kv_engine.cpp',
            'ontapkv_record_store.cpp',
            'ontapkv_cachemgr.cpp',
            'ontapkv_iomgr_mock.cpp',
            'ontapkv_iomgr_ipc.cpp',
            'ontapkv_recovery_unit_mock.cpp',
            'ontapkv_histogram.cpp',
	],
	)


